# Site settings
course_name: History of Magic
course_description: |
    a
    b
    c
course_semester: "Fall 1998"

baseurl: "/cosmos" # the subpath of your site, e.g. /blog/
url: "https://wonjun-seo.github.io/" # the base hostname & protocol for your site

schoolname: "COSMOS, UC Davis"
schoolurl: "https://cosmos.ucdavis.edu"

address: |
    Department of Statistics,
    University of California, Davis
    Davis, CA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
